######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 18 13:52:57 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += addressbook.h \
    finddialog.h
SOURCES += addressbook.cpp main.cpp \
    finddialog.cpp
